import { FoodFormState } from './types';

export const PRESET_TOMATO: FoodFormState = {
  commodity_id: 'CMD-001',
  commodity_name: 'Fresh Tomato',
  category: 'produce',
  moisture: 94.0,
  critical_moisture: 96.0,
  fat: 0.2,
  ph: 4.4,
  is_respiring: true,
  resp_o2: 15.0,
  resp_co2: 18.0,
  rq: 1.2,
  q10: 2.1,
  o2_target: 4.0,
  co2_tolerance: 4.0,
  shelf_life_days: 14,
  temp_c: 12.0,
  humidity_rh: 90.0,
  storage_type: 'chilled',
  transport_conditions: 'cold_chain',
  pack_weight_kg: 0.5,
  pack_area_m2: 0.08,
};

export const PRESET_BISCUITS: FoodFormState = {
  commodity_id: 'CMD-005',
  commodity_name: 'Crispy Biscuits / Cookies',
  category: 'dry',
  moisture: 3.0,
  critical_moisture: 6.0,
  fat: 16.0,
  ph: 7.0,
  is_respiring: false,
  resp_o2: 0.0,
  resp_co2: 0.0,
  rq: 1.0,
  q10: 1.0,
  o2_target: 0.0,
  co2_tolerance: 0.0,
  shelf_life_days: 180,
  temp_c: 25.0,
  humidity_rh: 65.0,
  storage_type: 'ambient',
  transport_conditions: 'ambient',
  pack_weight_kg: 0.25,
  pack_area_m2: 0.05,
};
